[workspace]
members = [
    "santazk",
    "zkretvm",
]

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/techiepriyansh/ZKretSanta"

[workspace.dependencies]
santazk = { path = "./santazk", version = "0.0.1" }